spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  ssl:
    enabled: true
    key-alias: localhost
    key-password: 123456
    key-store: D:\localhost.keystore
